repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-symlinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: no-commit-to-branch
        args:
          - --branch=main
      - id: trailing-whitespace

  - repo: https://github.com/alpa-team/pre-commit-hooks
    rev: v1.0
    hooks:
      - id: check-necessary-files
      - id: check-packit-file
      - id: source0-uses-version-macro
