name: Autoupdate Alpa repository

on:
  schedule:
    # every month on 10th day of the month, at 04:04 AM
    - cron: "4 4 10 * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Autoupdate Alpa repository
        uses: alpa-team/autoupdate-alpa-repo@v1.0
        with:
          email-name: fi-muni-packages@email.cz
          smtp-address: smtp.seznam.cz
          email-password: ${{ secrets.ALPA_MAIL_BOT_PASSWORD }}
          debug: true
